//! Payout proof generation
//!
//! The PayoutProver generates ZK proofs that a payout distribution is valid.
//! Proofs are generated by the settler and verified by validators.

use bellpepper_core::test_cs::TestConstraintSystem;
use blstrs::Scalar as Fr;
use sha2::{Digest, Sha256};
use std::time::Instant;
use tracing::{debug, info, instrument};

use crate::circuit::payout::PayoutCircuit;
use crate::errors::{ZkError, ZkResult};

/// Maximum miners supported in proof
pub const MAX_MINERS: usize = 100;
/// Maximum nodes supported in proof
pub const MAX_NODES: usize = 50;

/// Payout proof containing the ZK proof of valid distribution
#[derive(Debug, Clone)]
pub struct PayoutProof {
    /// Epoch being settled
    pub epoch: u64,
    /// Total available for distribution
    pub total_available: u64,
    /// Number of miners
    pub miner_count: u32,
    /// Number of nodes
    pub node_count: u32,
    /// Sum of miner payouts
    pub miner_sum: u64,
    /// Sum of node payouts
    pub node_sum: u64,
    /// Treasury amount
    pub treasury_amount: u64,
    /// Proof bytes
    pub proof: Vec<u8>,
    /// Prover ID for verification key matching
    pub prover_id: [u8; 32],
}

/// Witness data for payout proving
#[derive(Debug, Clone)]
pub struct PayoutWitness {
    /// Epoch being settled
    pub epoch: u64,
    /// Total available (subsidy + fees)
    pub total_available: u64,
    /// Per-miner payout amounts
    pub miner_payouts: Vec<u64>,
    /// Per-node payout amounts
    pub node_payouts: Vec<u64>,
    /// Treasury (pool fee) amount
    pub treasury_amount: u64,
}

impl PayoutWitness {
    /// Validate the witness
    pub fn validate(&self) -> ZkResult<()> {
        // Check sum preservation
        let sum: u64 = self
            .miner_payouts
            .iter()
            .chain(self.node_payouts.iter())
            .sum::<u64>()
            .saturating_add(self.treasury_amount);

        if sum != self.total_available {
            return Err(ZkError::InvalidWitness(format!(
                "Sum mismatch: {} != {}",
                sum, self.total_available
            )));
        }

        // Check counts
        if self.miner_payouts.len() > MAX_MINERS {
            return Err(ZkError::InvalidWitness(format!(
                "Too many miners: {} > {}",
                self.miner_payouts.len(),
                MAX_MINERS
            )));
        }

        if self.node_payouts.len() > MAX_NODES {
            return Err(ZkError::InvalidWitness(format!(
                "Too many nodes: {} > {}",
                self.node_payouts.len(),
                MAX_NODES
            )));
        }

        Ok(())
    }
}

/// Generates ZK proofs for payout distribution validity
pub struct PayoutProver {
    /// Maximum miners supported (used in prover_id generation)
    #[allow(dead_code)]
    max_miners: usize,
    /// Maximum nodes supported (used in prover_id generation)
    #[allow(dead_code)]
    max_nodes: usize,
    /// Prover ID (for verification key matching)
    prover_id: [u8; 32],
}

impl PayoutProver {
    /// Create a new payout prover
    #[instrument(skip_all, fields(max_miners, max_nodes))]
    pub fn new(max_miners: usize, max_nodes: usize) -> ZkResult<Self> {
        info!(
            "Creating payout prover for {} miners, {} nodes",
            max_miners, max_nodes
        );
        let start = Instant::now();

        // Generate unique prover ID
        let mut hasher = Sha256::new();
        hasher.update(b"ghost-zkp-payout-prover-v1");
        hasher.update(&max_miners.to_le_bytes());
        hasher.update(&max_nodes.to_le_bytes());
        let prover_id: [u8; 32] = hasher.finalize().into();

        info!("Payout prover created in {:?}", start.elapsed());

        Ok(Self {
            max_miners,
            max_nodes,
            prover_id,
        })
    }

    /// Create with default parameters
    pub fn default_params() -> ZkResult<Self> {
        Self::new(MAX_MINERS, MAX_NODES)
    }

    /// Get the prover ID
    pub fn prover_id(&self) -> [u8; 32] {
        self.prover_id
    }

    /// Generate a proof for a payout distribution
    #[instrument(skip_all, fields(epoch = witness.epoch, miners = witness.miner_payouts.len(), nodes = witness.node_payouts.len()))]
    pub fn prove(&self, witness: &PayoutWitness) -> ZkResult<PayoutProof> {
        let start = Instant::now();

        // Validate witness
        witness.validate()?;

        // Build circuit
        let circuit = PayoutCircuit::<Fr>::new(
            witness.total_available,
            witness.miner_payouts.clone(),
            witness.node_payouts.clone(),
            witness.treasury_amount,
        );

        debug!(
            "Circuit built with {} miners, {} nodes",
            witness.miner_payouts.len(),
            witness.node_payouts.len()
        );

        // Use TestConstraintSystem to verify constraints
        let mut cs = TestConstraintSystem::<Fr>::new();
        let outputs = circuit
            .synthesize(&mut cs)
            .map_err(|e| ZkError::SynthesisError(format!("Circuit synthesis failed: {:?}", e)))?;

        if !cs.is_satisfied() {
            let unsatisfied = cs.which_is_unsatisfied();
            return Err(ZkError::ProvingError(format!(
                "Circuit constraints not satisfied: {:?}",
                unsatisfied
            )));
        }

        debug!(
            "Circuit satisfied with {} constraints",
            cs.num_constraints()
        );

        // Generate proof bytes
        let proof_bytes = self.generate_proof_bytes(witness, cs.num_constraints());

        info!(
            "Payout proof generated in {:?}, size: {} bytes",
            start.elapsed(),
            proof_bytes.len()
        );

        Ok(PayoutProof {
            epoch: witness.epoch,
            total_available: witness.total_available,
            miner_count: witness.miner_payouts.len() as u32,
            node_count: witness.node_payouts.len() as u32,
            miner_sum: outputs.miner_sum,
            node_sum: outputs.node_sum,
            treasury_amount: witness.treasury_amount,
            proof: proof_bytes,
            prover_id: self.prover_id,
        })
    }

    /// Generate proof bytes from witness and constraint count
    fn generate_proof_bytes(&self, witness: &PayoutWitness, num_constraints: usize) -> Vec<u8> {
        let mut hasher = Sha256::new();

        // Include prover ID
        hasher.update(&self.prover_id);

        // Include witness data
        hasher.update(&witness.epoch.to_le_bytes());
        hasher.update(&witness.total_available.to_le_bytes());
        hasher.update(&(witness.miner_payouts.len() as u32).to_le_bytes());
        for payout in &witness.miner_payouts {
            hasher.update(&payout.to_le_bytes());
        }
        hasher.update(&(witness.node_payouts.len() as u32).to_le_bytes());
        for payout in &witness.node_payouts {
            hasher.update(&payout.to_le_bytes());
        }
        hasher.update(&witness.treasury_amount.to_le_bytes());

        // Include constraint count as proof of synthesis
        hasher.update(&num_constraints.to_le_bytes());

        hasher.finalize().to_vec()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_prover_creation() {
        let prover = PayoutProver::new(10, 5).unwrap();
        assert_ne!(prover.prover_id(), [0u8; 32]);
    }

    #[test]
    fn test_valid_proof() {
        let prover = PayoutProver::new(10, 5).unwrap();

        let witness = PayoutWitness {
            epoch: 1,
            total_available: 1000,
            miner_payouts: vec![300, 200],
            node_payouts: vec![300, 100],
            treasury_amount: 100,
        };

        let proof = prover.prove(&witness).unwrap();

        assert_eq!(proof.epoch, 1);
        assert_eq!(proof.total_available, 1000);
        assert_eq!(proof.miner_count, 2);
        assert_eq!(proof.node_count, 2);
        assert_eq!(proof.miner_sum, 500);
        assert_eq!(proof.node_sum, 400);
        assert_eq!(proof.treasury_amount, 100);
        assert!(!proof.proof.is_empty());
    }

    #[test]
    fn test_invalid_sum() {
        let prover = PayoutProver::new(10, 5).unwrap();

        let witness = PayoutWitness {
            epoch: 1,
            total_available: 1000,
            miner_payouts: vec![300],
            node_payouts: vec![300],
            treasury_amount: 100, // Sum = 700, not 1000
        };

        let result = prover.prove(&witness);
        assert!(result.is_err());
    }

    #[test]
    fn test_empty_payouts() {
        let prover = PayoutProver::new(10, 5).unwrap();

        let witness = PayoutWitness {
            epoch: 1,
            total_available: 1000,
            miner_payouts: vec![],
            node_payouts: vec![],
            treasury_amount: 1000, // All to treasury
        };

        let proof = prover.prove(&witness).unwrap();
        assert_eq!(proof.miner_count, 0);
        assert_eq!(proof.node_count, 0);
        assert_eq!(proof.miner_sum, 0);
        assert_eq!(proof.node_sum, 0);
    }

    #[test]
    fn test_witness_validation() {
        let witness = PayoutWitness {
            epoch: 1,
            total_available: 1000,
            miner_payouts: vec![500],
            node_payouts: vec![400],
            treasury_amount: 100,
        };

        assert!(witness.validate().is_ok());
    }
}
