//! Payout proof generation
//!
//! The PayoutProver generates ZK proofs that a payout distribution is valid.
//! Proofs are generated by the settler and verified by validators.
//!
//! # Groth16 Implementation
//!
//! This module uses Groth16 proofs on the BLS12-381 curve via bellpepper.
//! Proof generation takes ~2 seconds, verification takes ~10ms.
//!
//! # SECURITY WARNING: Trusted Setup Required
//!
//! **Groth16 requires a trusted setup ceremony (MPC).**
//!
//! The security of Groth16 proofs depends entirely on the trusted setup:
//! - If the "toxic waste" from setup is known, anyone can forge proofs
//! - A single malicious participant in setup can compromise the system
//!
//! For production use:
//! 1. **NEVER** use `generate_random_parameters` in production
//! 2. Use parameters from a multi-party computation (MPC) ceremony
//! 3. Verify the ceremony transcript before using parameters
//! 4. See `docs/ZK_TRUSTED_SETUP.md` for ceremony requirements
//!
//! The `new_with_setup` constructor is provided for testing only.
//! Production deployments MUST use `new_with_params` with MPC-generated parameters.

use bellperson::{
    groth16::{
        create_random_proof, generate_random_parameters, prepare_verifying_key, Parameters,
        PreparedVerifyingKey,
    },
    util_cs::test_cs::TestConstraintSystem,
};
use blstrs::{Bls12, Scalar as Fr};
use sha2::{Digest, Sha256};
use std::sync::Arc;
use std::time::Instant;
use tracing::{debug, info, instrument, warn};

use crate::circuit::payout::PayoutCircuit;
use crate::errors::{ZkError, ZkResult};
use crate::types::GROTH16_PROOF_SIZE;

/// Maximum miners supported in proof
pub const MAX_MINERS: usize = 100;
/// Maximum nodes supported in proof
pub const MAX_NODES: usize = 50;

/// Payout proof containing the ZK proof of valid distribution
#[derive(Debug, Clone)]
pub struct PayoutProof {
    /// Epoch being settled
    pub epoch: u64,
    /// Total available for distribution
    pub total_available: u64,
    /// Number of miners
    pub miner_count: u32,
    /// Number of nodes
    pub node_count: u32,
    /// Sum of miner payouts
    pub miner_sum: u64,
    /// Sum of node payouts
    pub node_sum: u64,
    /// Treasury amount
    pub treasury_amount: u64,
    /// Proof bytes
    pub proof: Vec<u8>,
    /// Prover ID for verification key matching
    pub prover_id: [u8; 32],
}

/// Witness data for payout proving
#[derive(Debug, Clone)]
pub struct PayoutWitness {
    /// Epoch being settled
    pub epoch: u64,
    /// Total available (subsidy + fees)
    pub total_available: u64,
    /// Per-miner payout amounts
    pub miner_payouts: Vec<u64>,
    /// Per-node payout amounts
    pub node_payouts: Vec<u64>,
    /// Treasury (pool fee) amount
    pub treasury_amount: u64,
}

impl PayoutWitness {
    /// Validate the witness
    pub fn validate(&self) -> ZkResult<()> {
        // Check sum preservation using checked arithmetic to detect overflow
        let payouts_sum: u64 = self
            .miner_payouts
            .iter()
            .chain(self.node_payouts.iter())
            .try_fold(0u64, |acc, &x| acc.checked_add(x))
            .ok_or_else(|| ZkError::InvalidWitness("Payouts sum overflowed u64".to_string()))?;

        let sum = payouts_sum
            .checked_add(self.treasury_amount)
            .ok_or_else(|| ZkError::InvalidWitness("Total sum overflowed u64".to_string()))?;

        if sum != self.total_available {
            return Err(ZkError::InvalidWitness(format!(
                "Sum mismatch: {} != {}",
                sum, self.total_available
            )));
        }

        // Check counts
        if self.miner_payouts.len() > MAX_MINERS {
            return Err(ZkError::InvalidWitness(format!(
                "Too many miners: {} > {}",
                self.miner_payouts.len(),
                MAX_MINERS
            )));
        }

        if self.node_payouts.len() > MAX_NODES {
            return Err(ZkError::InvalidWitness(format!(
                "Too many nodes: {} > {}",
                self.node_payouts.len(),
                MAX_NODES
            )));
        }

        Ok(())
    }
}

/// Generates ZK proofs for payout distribution validity
///
/// The prover holds Groth16 parameters generated during setup.
/// Parameters are deterministic based on the circuit structure (max miners/nodes).
pub struct PayoutProver {
    /// Maximum miners supported
    max_miners: usize,
    /// Maximum nodes supported
    max_nodes: usize,
    /// Prover ID (for verification key matching)
    prover_id: [u8; 32],
    /// Groth16 proving parameters (generated during setup)
    params: Option<Arc<Parameters<Bls12>>>,
    /// Prepared verifying key for efficient verification
    prepared_vk: Option<Arc<PreparedVerifyingKey<Bls12>>>,
}

impl PayoutProver {
    /// Create a new payout prover with Groth16 parameter generation
    ///
    /// This performs the trusted setup for the circuit. In production,
    /// parameters should be generated once and stored, not regenerated.
    #[instrument(skip_all, fields(max_miners, max_nodes))]
    pub fn new(max_miners: usize, max_nodes: usize) -> ZkResult<Self> {
        info!(
            "Creating payout prover for {} miners, {} nodes",
            max_miners, max_nodes
        );
        let start = Instant::now();

        // Generate unique prover ID based on circuit parameters
        let mut hasher = Sha256::new();
        hasher.update(b"ghost-zkp-payout-prover-v2-groth16");
        hasher.update(max_miners.to_le_bytes());
        hasher.update(max_nodes.to_le_bytes());
        let prover_id: [u8; 32] = hasher.finalize().into();

        info!("Payout prover created in {:?}", start.elapsed());

        Ok(Self {
            max_miners,
            max_nodes,
            prover_id,
            params: None,
            prepared_vk: None,
        })
    }

    /// Create a new payout prover with full Groth16 setup
    ///
    /// **SECURITY WARNING: FOR TESTING ONLY**
    ///
    /// This generates the proving and verifying keys using random toxic waste.
    /// This is convenient for testing but **INSECURE FOR PRODUCTION**:
    /// - The toxic waste exists in memory and could be extracted
    /// - Anyone with the toxic waste can forge proofs
    /// - This bypasses the security of the ZK proof system
    ///
    /// For production, use `new_with_params()` with MPC-generated parameters.
    /// See `docs/ZK_TRUSTED_SETUP.md` for ceremony requirements.
    ///
    /// # Arguments
    /// * `max_miners` - Maximum number of miners (affects circuit size)
    /// * `max_nodes` - Maximum number of nodes (affects circuit size)
    #[instrument(skip_all, fields(max_miners, max_nodes))]
    pub fn new_with_setup(max_miners: usize, max_nodes: usize) -> ZkResult<Self> {
        warn!(
            "SECURITY WARNING: Using random trusted setup. \
             This is INSECURE for production. Use MPC-generated parameters."
        );
        info!(
            "Creating payout prover with Groth16 setup for {} miners, {} nodes",
            max_miners, max_nodes
        );
        let start = Instant::now();

        // Generate unique prover ID
        let mut hasher = Sha256::new();
        hasher.update(b"ghost-zkp-payout-prover-v2-groth16");
        hasher.update(max_miners.to_le_bytes());
        hasher.update(max_nodes.to_le_bytes());
        let prover_id: [u8; 32] = hasher.finalize().into();

        // Create dummy circuit for parameter generation
        let dummy_circuit = PayoutCircuit::<Fr>::dummy(max_miners, max_nodes);

        // Generate Groth16 parameters (trusted setup)
        // SECURITY: This uses random toxic waste - FOR TESTING ONLY
        // Production MUST use MPC-generated parameters
        info!("Generating Groth16 parameters (TESTING ONLY - NOT SECURE FOR PRODUCTION)...");
        let setup_start = Instant::now();
        // H-3 FIX: Use OsRng for cryptographic security instead of thread_rng()
        let params =
            generate_random_parameters::<Bls12, _, _>(dummy_circuit, &mut rand::rngs::OsRng)
                .map_err(|e| {
                    ZkError::SetupError(format!("Parameter generation failed: {:?}", e))
                })?;

        info!(
            "Groth16 parameters generated in {:?}",
            setup_start.elapsed()
        );

        // Prepare verifying key for efficient verification
        let prepared_vk = prepare_verifying_key(&params.vk);

        info!(
            "Payout prover with Groth16 setup created in {:?}",
            start.elapsed()
        );

        Ok(Self {
            max_miners,
            max_nodes,
            prover_id,
            params: Some(Arc::new(params)),
            prepared_vk: Some(Arc::new(prepared_vk)),
        })
    }

    /// Create with default parameters (no Groth16 setup)
    pub fn default_params() -> ZkResult<Self> {
        Self::new(MAX_MINERS, MAX_NODES)
    }

    /// Create with default parameters and full Groth16 setup
    pub fn default_params_with_setup() -> ZkResult<Self> {
        Self::new_with_setup(MAX_MINERS, MAX_NODES)
    }

    /// Get the prover ID
    pub fn prover_id(&self) -> [u8; 32] {
        self.prover_id
    }

    /// Get the prepared verifying key (for external verification)
    pub fn prepared_verifying_key(&self) -> Option<Arc<PreparedVerifyingKey<Bls12>>> {
        self.prepared_vk.clone()
    }

    /// Check if Groth16 parameters are available
    pub fn has_groth16_params(&self) -> bool {
        self.params.is_some()
    }

    /// Generate a proof for a payout distribution
    ///
    /// If Groth16 parameters are available, generates a real cryptographic proof.
    /// Otherwise, falls back to a simulated proof (for testing/development).
    #[instrument(skip_all, fields(epoch = witness.epoch, miners = witness.miner_payouts.len(), nodes = witness.node_payouts.len()))]
    pub fn prove(&self, witness: &PayoutWitness) -> ZkResult<PayoutProof> {
        let start = Instant::now();

        // Validate witness
        witness.validate()?;

        // For Groth16, we need to pad the witness to match the setup parameters
        // The circuit structure must be identical between setup and proving
        let (padded_miner_payouts, padded_node_payouts) = if self.params.is_some() {
            // Pad to match setup parameters
            let mut miners = witness.miner_payouts.clone();
            let mut nodes = witness.node_payouts.clone();
            miners.resize(self.max_miners, 0);
            nodes.resize(self.max_nodes, 0);
            (miners, nodes)
        } else {
            // No padding needed for simulated proofs
            (witness.miner_payouts.clone(), witness.node_payouts.clone())
        };

        // Track actual counts for metadata commitment (before padding)
        let actual_miner_count = witness.miner_payouts.len() as u32;
        let actual_node_count = witness.node_payouts.len() as u32;

        // Build circuit for constraint verification (with padding for Groth16)
        // Use new_with_counts to preserve actual miner/node counts for metadata commitment
        let circuit = PayoutCircuit::<Fr>::new_with_counts(
            witness.total_available,
            padded_miner_payouts.clone(),
            padded_node_payouts.clone(),
            witness.treasury_amount,
            witness.epoch,
            actual_miner_count,
            actual_node_count,
        );

        debug!(
            "Circuit built with {} miners, {} nodes (padded from {}, {}), epoch={}",
            padded_miner_payouts.len(),
            padded_node_payouts.len(),
            actual_miner_count,
            actual_node_count,
            witness.epoch
        );

        // First verify constraints with TestConstraintSystem
        let test_circuit = PayoutCircuit::<Fr>::new_with_counts(
            witness.total_available,
            padded_miner_payouts.clone(),
            padded_node_payouts.clone(),
            witness.treasury_amount,
            witness.epoch,
            actual_miner_count,
            actual_node_count,
        );
        let mut cs = TestConstraintSystem::<Fr>::new();
        let outputs = test_circuit
            .synthesize(&mut cs)
            .map_err(|e| ZkError::SynthesisError(format!("Circuit synthesis failed: {:?}", e)))?;

        if !cs.is_satisfied() {
            let unsatisfied = cs.which_is_unsatisfied();
            return Err(ZkError::ProvingError(format!(
                "Circuit constraints not satisfied: {:?}",
                unsatisfied
            )));
        }

        debug!(
            "Circuit satisfied with {} constraints",
            cs.num_constraints()
        );

        // Generate proof bytes
        let proof_bytes = if let Some(ref params) = self.params {
            self.generate_groth16_proof(circuit, params)?
        } else {
            // In test builds, fall back to simulated proofs for convenience.
            // In release builds, Groth16 parameters are REQUIRED — refuse to produce a proof.
            #[cfg(test)]
            {
                warn!("Groth16 parameters not available, using simulated proof (test mode)");
                self.generate_simulated_proof(witness, cs.num_constraints())
            }
            #[cfg(not(test))]
            {
                return Err(ZkError::ProvingError(
                    "Groth16 parameters not loaded — cannot generate proof. \
                     Load MPC-generated parameters via new_with_params() before proving."
                        .to_string(),
                ));
            }
        };

        info!(
            "Payout proof generated in {:?}, size: {} bytes, groth16: {}",
            start.elapsed(),
            proof_bytes.len(),
            self.params.is_some()
        );

        Ok(PayoutProof {
            epoch: witness.epoch,
            total_available: witness.total_available,
            miner_count: witness.miner_payouts.len() as u32,
            node_count: witness.node_payouts.len() as u32,
            miner_sum: outputs.miner_sum,
            node_sum: outputs.node_sum,
            treasury_amount: witness.treasury_amount,
            proof: proof_bytes,
            prover_id: self.prover_id,
        })
    }

    /// Generate a real Groth16 proof
    fn generate_groth16_proof(
        &self,
        circuit: PayoutCircuit<Fr>,
        params: &Parameters<Bls12>,
    ) -> ZkResult<Vec<u8>> {
        let proving_start = Instant::now();

        // Generate the Groth16 proof
        // H-3 FIX: Use OsRng for cryptographic security instead of thread_rng()
        let proof = create_random_proof(circuit, params, &mut rand::rngs::OsRng)
            .map_err(|e| ZkError::ProvingError(format!("Groth16 proving failed: {:?}", e)))?;

        debug!("Groth16 proof generated in {:?}", proving_start.elapsed());

        // Serialize the proof
        let mut proof_bytes = Vec::with_capacity(GROTH16_PROOF_SIZE);

        // Serialize A (G1 point)
        let a_bytes = proof.a.to_compressed();
        proof_bytes.extend_from_slice(&a_bytes);

        // Serialize B (G2 point)
        let b_bytes = proof.b.to_compressed();
        proof_bytes.extend_from_slice(&b_bytes);

        // Serialize C (G1 point)
        let c_bytes = proof.c.to_compressed();
        proof_bytes.extend_from_slice(&c_bytes);

        Ok(proof_bytes)
    }

    /// Generate a simulated proof (for testing when Groth16 params aren't available)
    #[cfg(test)]
    fn generate_simulated_proof(&self, witness: &PayoutWitness, num_constraints: usize) -> Vec<u8> {
        let mut hasher = Sha256::new();

        // Include prover ID
        hasher.update(self.prover_id);

        // Include witness data
        hasher.update(witness.epoch.to_le_bytes());
        hasher.update(witness.total_available.to_le_bytes());
        hasher.update((witness.miner_payouts.len() as u32).to_le_bytes());
        for payout in &witness.miner_payouts {
            hasher.update(payout.to_le_bytes());
        }
        hasher.update((witness.node_payouts.len() as u32).to_le_bytes());
        for payout in &witness.node_payouts {
            hasher.update(payout.to_le_bytes());
        }
        hasher.update(witness.treasury_amount.to_le_bytes());

        // Include constraint count as proof of synthesis
        hasher.update(num_constraints.to_le_bytes());

        hasher.finalize().to_vec()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_prover_creation() {
        let prover = PayoutProver::new(10, 5).unwrap();
        assert_ne!(prover.prover_id(), [0u8; 32]);
    }

    #[test]
    fn test_valid_proof() {
        let prover = PayoutProver::new(10, 5).unwrap();

        let witness = PayoutWitness {
            epoch: 1,
            total_available: 1000,
            miner_payouts: vec![300, 200],
            node_payouts: vec![300, 100],
            treasury_amount: 100,
        };

        let proof = prover.prove(&witness).unwrap();

        assert_eq!(proof.epoch, 1);
        assert_eq!(proof.total_available, 1000);
        assert_eq!(proof.miner_count, 2);
        assert_eq!(proof.node_count, 2);
        assert_eq!(proof.miner_sum, 500);
        assert_eq!(proof.node_sum, 400);
        assert_eq!(proof.treasury_amount, 100);
        assert!(!proof.proof.is_empty());
    }

    #[test]
    fn test_invalid_sum() {
        let prover = PayoutProver::new(10, 5).unwrap();

        let witness = PayoutWitness {
            epoch: 1,
            total_available: 1000,
            miner_payouts: vec![300],
            node_payouts: vec![300],
            treasury_amount: 100, // Sum = 700, not 1000
        };

        let result = prover.prove(&witness);
        assert!(result.is_err());
    }

    #[test]
    fn test_empty_payouts() {
        let prover = PayoutProver::new(10, 5).unwrap();

        let witness = PayoutWitness {
            epoch: 1,
            total_available: 1000,
            miner_payouts: vec![],
            node_payouts: vec![],
            treasury_amount: 1000, // All to treasury
        };

        let proof = prover.prove(&witness).unwrap();
        assert_eq!(proof.miner_count, 0);
        assert_eq!(proof.node_count, 0);
        assert_eq!(proof.miner_sum, 0);
        assert_eq!(proof.node_sum, 0);
    }

    #[test]
    fn test_witness_validation() {
        let witness = PayoutWitness {
            epoch: 1,
            total_available: 1000,
            miner_payouts: vec![500],
            node_payouts: vec![400],
            treasury_amount: 100,
        };

        assert!(witness.validate().is_ok());
    }

    // ZK-M3: Test overflow detection in witness validation
    #[test]
    fn test_witness_validation_overflow() {
        // Test overflow in payouts sum
        let witness = PayoutWitness {
            epoch: 1,
            total_available: u64::MAX,
            miner_payouts: vec![u64::MAX, 1], // This should overflow
            node_payouts: vec![],
            treasury_amount: 0,
        };

        let result = witness.validate();
        assert!(result.is_err());
        assert!(result.unwrap_err().to_string().contains("overflow"));
    }

    #[test]
    fn test_witness_validation_treasury_overflow() {
        // Test overflow when adding treasury
        let witness = PayoutWitness {
            epoch: 1,
            total_available: u64::MAX,
            miner_payouts: vec![u64::MAX - 100],
            node_payouts: vec![],
            treasury_amount: 101, // This should overflow when added
        };

        let result = witness.validate();
        assert!(result.is_err());
        assert!(result.unwrap_err().to_string().contains("overflow"));
    }
}
