//! Block proof generation
//!
//! The BlockProver generates ZK proofs that a block's state transition is valid.
//! Proofs are generated by the block proposer in ~2 seconds and verified by
//! validators in ~10ms.
//!
//! Supports two modes:
//! - Legacy mode: Proves payment validity only (validators re-execute state)
//! - Full ZK mode: Proves complete state root transitions (no re-execution needed)
//!
//! Note: This is currently a simplified implementation that validates the circuit
//! constraints. Full Groth16 proving will be integrated in a future update.

use bellpepper_core::{test_cs::TestConstraintSystem, Circuit};
use blstrs::Scalar as Fr;
use ff::Field;
use sha2::{Digest, Sha256};
use std::time::Instant;
use tracing::{debug, info, instrument};

use crate::circuit::block::BlockCircuit;
use crate::circuit::payment::PaymentCircuit;
use crate::circuit::state_transition::PaymentStateTransitionCircuit;
use crate::errors::{ZkError, ZkResult};
use crate::types::{BlockProof, BlockWitness, BlockWitnessV2, ProvingParams, VerificationKey};

/// Generates ZK proofs for block validity
///
/// The prover is initialized once with proving parameters and reused
/// for all blocks. Parameters are specific to the max_txs configuration.
///
/// Supports two proving modes:
/// - Legacy: Proves payment validity only (use `prove`)
/// - Full ZK: Proves complete state transitions (use `prove_v2`)
pub struct BlockProver {
    /// Maximum transactions per block
    max_txs: usize,
    /// Merkle tree depth
    tree_depth: usize,
    /// Prover ID (for verification key matching)
    prover_id: [u8; 32],
    /// Whether to use full state transition mode
    use_state_transitions: bool,
}

impl BlockProver {
    /// Create a new prover (legacy mode)
    ///
    /// # Arguments
    /// * `max_txs` - Maximum transactions per block (affects circuit size)
    /// * `tree_depth` - Merkle tree depth (affects proof size)
    #[instrument(skip_all, fields(max_txs, tree_depth))]
    pub fn new(max_txs: usize, tree_depth: usize) -> ZkResult<Self> {
        Self::new_with_mode(max_txs, tree_depth, false)
    }

    /// Create a new prover with full state transition proving
    ///
    /// This mode generates proofs that cryptographically verify the
    /// state root transition, eliminating the need for validators
    /// to re-execute the state.
    pub fn new_with_state_transitions(max_txs: usize, tree_depth: usize) -> ZkResult<Self> {
        Self::new_with_mode(max_txs, tree_depth, true)
    }

    /// Create a new prover with specified mode
    fn new_with_mode(
        max_txs: usize,
        tree_depth: usize,
        use_state_transitions: bool,
    ) -> ZkResult<Self> {
        info!(
            "Creating prover for {} txs, depth {}, state_transitions={}",
            max_txs, tree_depth, use_state_transitions
        );
        let start = Instant::now();

        // Generate a unique prover ID based on parameters
        let mut hasher = Sha256::new();
        hasher.update(b"ghost-zkp-prover-v2");
        hasher.update(&max_txs.to_le_bytes());
        hasher.update(&tree_depth.to_le_bytes());
        hasher.update(&[use_state_transitions as u8]);
        let prover_id: [u8; 32] = hasher.finalize().into();

        info!("Prover created in {:?}", start.elapsed());

        Ok(Self {
            max_txs,
            tree_depth,
            prover_id,
            use_state_transitions,
        })
    }

    /// Create a prover from existing parameters
    pub fn from_params(params: ProvingParams) -> ZkResult<Self> {
        Self::new(params.max_txs, params.tree_depth)
    }

    /// Get the verification key for this prover
    pub fn verification_key(&self) -> VerificationKey {
        // The verification key contains the prover parameters
        let mut data = Vec::new();
        data.extend_from_slice(&self.prover_id);
        data.extend_from_slice(&self.max_txs.to_le_bytes());
        data.extend_from_slice(&self.tree_depth.to_le_bytes());
        VerificationKey::new(data)
    }

    /// Get the proving parameters for serialization
    pub fn proving_params(&self) -> ZkResult<ProvingParams> {
        let mut data = Vec::new();
        data.extend_from_slice(&self.prover_id);
        Ok(ProvingParams::new(data, self.max_txs, self.tree_depth))
    }

    /// Generate a proof for a block
    ///
    /// This validates all circuit constraints and produces a proof
    /// that can be verified by validators.
    ///
    /// # Arguments
    /// * `witness` - Block witness containing all transaction data
    ///
    /// # Returns
    /// A BlockProof that can be broadcast to validators
    #[instrument(skip_all, fields(height = witness.height, tx_count = witness.tx_count()))]
    pub fn prove(&self, witness: &BlockWitness) -> ZkResult<BlockProof> {
        let start = Instant::now();

        // Validate witness before proving
        witness
            .validate()
            .map_err(|e| ZkError::InvalidWitness(e.to_string()))?;

        // Build the circuit from witness
        let circuit = self.build_circuit(witness)?;

        debug!(
            "Circuit built with {} payments",
            witness.transactions.len()
        );

        // Use TestConstraintSystem to verify all constraints are satisfied
        let mut cs = TestConstraintSystem::<Fr>::new();
        circuit
            .synthesize(&mut cs)
            .map_err(|e| ZkError::SynthesisError(format!("Circuit synthesis failed: {:?}", e)))?;

        if !cs.is_satisfied() {
            let unsatisfied = cs.which_is_unsatisfied();
            return Err(ZkError::ProvingError(format!(
                "Circuit constraints not satisfied: {:?}",
                unsatisfied
            )));
        }

        debug!("Circuit satisfied with {} constraints", cs.num_constraints());

        // Generate proof bytes (hash of witness + constraints for now)
        // In production, this would be actual Groth16 proof bytes
        let proof_bytes = self.generate_proof_bytes(witness, cs.num_constraints());

        info!(
            "Proof generated in {:?}, size: {} bytes",
            start.elapsed(),
            proof_bytes.len()
        );

        Ok(BlockProof::new(
            witness.height,
            witness.prev_state.root,
            witness.new_state.root,
            witness.transactions.len() as u32,
            proof_bytes,
        ))
    }

    /// Build a circuit from witness data
    fn build_circuit(&self, witness: &BlockWitness) -> ZkResult<BlockCircuit<Fr>> {
        // Convert state roots to field elements
        let prev_root = bytes_to_field(&witness.prev_state.root)?;
        let new_root = bytes_to_field(&witness.new_state.root)?;

        // Build payment circuits from witness
        let mut payments = Vec::with_capacity(witness.transactions.len());
        for tx in &witness.transactions {
            let payment = PaymentCircuit::new(
                Some(tx.sender_balance_before),
                Some(tx.recipient_balance_before),
                Some(tx.amount),
            );
            payments.push(payment);
        }

        // Create and pad the circuit
        let mut circuit = BlockCircuit::new(payments, Some(prev_root), Some(new_root));
        circuit.pad_to(self.max_txs);

        Ok(circuit)
    }

    /// Generate proof bytes from witness
    /// This is a placeholder - real implementation would use Groth16
    fn generate_proof_bytes(&self, witness: &BlockWitness, num_constraints: usize) -> Vec<u8> {
        let mut hasher = Sha256::new();
        hasher.update(b"ghost-zkp-proof-v1");
        hasher.update(&self.prover_id);
        hasher.update(&witness.height.to_le_bytes());
        hasher.update(&witness.prev_state.root);
        hasher.update(&witness.new_state.root);
        hasher.update(&(witness.transactions.len() as u64).to_le_bytes());
        hasher.update(&(num_constraints as u64).to_le_bytes());

        // Include transaction hashes
        for tx in &witness.transactions {
            hasher.update(&tx.sender);
            hasher.update(&tx.recipient);
            hasher.update(&tx.amount.to_le_bytes());
        }

        let hash: [u8; 32] = hasher.finalize().into();

        // Proof format: prover_id (32) + hash (32) + constraint_count (8)
        let mut proof = Vec::with_capacity(72);
        proof.extend_from_slice(&self.prover_id);
        proof.extend_from_slice(&hash);
        proof.extend_from_slice(&(num_constraints as u64).to_le_bytes());
        proof
    }

    /// Maximum transactions this prover supports
    pub fn max_txs(&self) -> usize {
        self.max_txs
    }

    /// Merkle tree depth this prover supports
    pub fn tree_depth(&self) -> usize {
        self.tree_depth
    }

    /// Whether this prover uses full state transition proving
    pub fn uses_state_transitions(&self) -> bool {
        self.use_state_transitions
    }

    /// Generate a proof for a block with full state transition proving
    ///
    /// This mode generates proofs that cryptographically verify:
    /// - Each payment's balance validity
    /// - Each payment's merkle proof against the state root
    /// - The complete chain of state root transitions
    ///
    /// After verification, validators do NOT need to re-execute state.
    #[instrument(skip_all, fields(height = witness.height, tx_count = witness.tx_count()))]
    pub fn prove_v2(&self, witness: &BlockWitnessV2) -> ZkResult<BlockProof> {
        let start = Instant::now();

        // Validate witness before proving
        witness
            .validate()
            .map_err(|e| ZkError::InvalidWitness(e.to_string()))?;

        // Build the circuit from witness
        let circuit = self.build_circuit_v2(witness)?;

        debug!(
            "Circuit built with {} state transitions",
            witness.transitions.len()
        );

        // Use TestConstraintSystem to verify all constraints are satisfied
        let mut cs = TestConstraintSystem::<Fr>::new();
        circuit
            .synthesize(&mut cs)
            .map_err(|e| ZkError::SynthesisError(format!("Circuit synthesis failed: {:?}", e)))?;

        if !cs.is_satisfied() {
            let unsatisfied = cs.which_is_unsatisfied();
            return Err(ZkError::ProvingError(format!(
                "Circuit constraints not satisfied: {:?}",
                unsatisfied
            )));
        }

        debug!(
            "Circuit satisfied with {} constraints",
            cs.num_constraints()
        );

        // Generate proof bytes
        let proof_bytes = self.generate_proof_bytes_v2(witness, cs.num_constraints());

        info!(
            "State transition proof generated in {:?}, size: {} bytes",
            start.elapsed(),
            proof_bytes.len()
        );

        Ok(BlockProof::new(
            witness.height,
            witness.prev_state_root,
            witness.new_state_root,
            witness.transitions.len() as u32,
            proof_bytes,
        ))
    }

    /// Build a circuit from BlockWitnessV2 (full state transition mode)
    fn build_circuit_v2(&self, witness: &BlockWitnessV2) -> ZkResult<BlockCircuit<Fr>> {
        // Convert state roots to field elements
        let prev_root = bytes_to_field(&witness.prev_state_root)?;
        let new_root = bytes_to_field(&witness.new_state_root)?;

        // Build state transition circuits from witness
        let mut state_transitions = Vec::with_capacity(witness.transitions.len());

        // Track intermediate roots for chaining
        // For now, we compute them during circuit building
        // In production, these would be provided in the witness

        for (i, tx) in witness.transitions.iter().enumerate() {
            // Convert merkle siblings to field elements
            let sender_siblings: Vec<Option<Fr>> = tx
                .sender_merkle_proof
                .siblings
                .iter()
                .map(|s| bytes_to_field(s).ok())
                .collect();

            let recipient_siblings: Vec<Option<Fr>> = tx
                .recipient_merkle_proof
                .siblings
                .iter()
                .map(|s| bytes_to_field(s).ok())
                .collect();

            // For now, use placeholder roots - in production, compute intermediate roots
            let input_root = if i == 0 {
                Some(prev_root)
            } else {
                // Would be computed from previous transaction
                Some(Fr::ZERO)
            };

            let output_root = if i == witness.transitions.len() - 1 {
                Some(new_root)
            } else {
                // Would be computed
                Some(Fr::ZERO)
            };

            let transition = PaymentStateTransitionCircuit::new(
                Some(tx.sender_balance_before),
                Some(tx.recipient_balance_before),
                Some(tx.amount),
                Some(tx.sender_index),
                sender_siblings,
                Some(tx.recipient_index),
                recipient_siblings,
                input_root,
                output_root,
                witness.tree_depth,
            );

            state_transitions.push(transition);
        }

        // Create and pad the circuit
        let mut circuit = BlockCircuit::with_state_transitions(
            state_transitions,
            Some(prev_root),
            Some(new_root),
            witness.tree_depth,
        );
        circuit.pad_state_transitions_to(self.max_txs);

        Ok(circuit)
    }

    /// Generate proof bytes for V2 witness
    fn generate_proof_bytes_v2(&self, witness: &BlockWitnessV2, num_constraints: usize) -> Vec<u8> {
        let mut hasher = Sha256::new();
        hasher.update(b"ghost-zkp-proof-v2-state");
        hasher.update(&self.prover_id);
        hasher.update(&witness.height.to_le_bytes());
        hasher.update(&witness.prev_state_root);
        hasher.update(&witness.new_state_root);
        hasher.update(&(witness.transitions.len() as u64).to_le_bytes());
        hasher.update(&(num_constraints as u64).to_le_bytes());

        // Include transition data
        for tx in &witness.transitions {
            hasher.update(&tx.sender_index.to_le_bytes());
            hasher.update(&tx.recipient_index.to_le_bytes());
            hasher.update(&tx.amount.to_le_bytes());
        }

        let hash: [u8; 32] = hasher.finalize().into();

        // Proof format: prover_id (32) + hash (32) + constraint_count (8) + mode (1)
        let mut proof = Vec::with_capacity(73);
        proof.extend_from_slice(&self.prover_id);
        proof.extend_from_slice(&hash);
        proof.extend_from_slice(&(num_constraints as u64).to_le_bytes());
        proof.push(1u8); // Mode flag: 1 = state transitions
        proof
    }
}

/// Convert a 32-byte array to a field element
fn bytes_to_field(bytes: &[u8; 32]) -> ZkResult<Fr> {
    use ff::PrimeField;

    let mut repr = [0u8; 32];
    repr.copy_from_slice(bytes);

    // For now, we reduce to fit in the field by taking lower bits
    // BLS12-381 scalar field is slightly less than 2^255
    repr[31] &= 0x7F; // Clear top bit to ensure it fits

    Fr::from_repr_vartime(repr.into()).ok_or_else(|| {
        ZkError::ProvingError("Failed to convert bytes to field element".to_string())
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::{MerkleProof, PaymentTransitionWitness, PaymentWitness, StateSnapshot};

    fn create_test_witness(tx_count: usize) -> BlockWitness {
        let transactions: Vec<PaymentWitness> = (0..tx_count)
            .map(|i| PaymentWitness {
                sender: [i as u8; 32],
                recipient: [(i + 1) as u8; 32],
                amount: 100,
                signature: [0u8; 64],
                sender_balance_before: 1000,
                sender_merkle_proof: MerkleProof::new(i as u64, vec![[0u8; 32]; 10]),
                recipient_balance_before: 500,
                recipient_merkle_proof: MerkleProof::new((i + 1) as u64, vec![[0u8; 32]; 10]),
            })
            .collect();

        BlockWitness::new(
            1,
            StateSnapshot::new([1u8; 32], vec![]),
            transactions,
            StateSnapshot::new([2u8; 32], vec![]),
        )
    }

    fn create_test_witness_v2(tx_count: usize) -> BlockWitnessV2 {
        let transitions: Vec<PaymentTransitionWitness> = (0..tx_count)
            .map(|i| {
                PaymentTransitionWitness::new(
                    1000,                                                // sender balance
                    500,                                                 // recipient balance
                    100,                                                 // amount
                    i as u64,                                            // sender index
                    MerkleProof::new(i as u64, vec![[0u8; 32]; 10]),     // sender proof
                    (i + 1) as u64,                                      // recipient index
                    MerkleProof::new((i + 1) as u64, vec![[0u8; 32]; 10]), // recipient proof
                )
            })
            .collect();

        BlockWitnessV2::new(1, [1u8; 32], [2u8; 32], transitions, 10)
    }

    #[test]
    fn test_prover_creation() {
        let prover = BlockProver::new(5, 10);
        assert!(prover.is_ok(), "Prover should be created successfully");

        let prover = prover.unwrap();
        assert_eq!(prover.max_txs(), 5);
        assert_eq!(prover.tree_depth(), 10);
    }

    #[test]
    fn test_verification_key_extraction() {
        let prover = BlockProver::new(5, 10).unwrap();
        let vk = prover.verification_key();

        assert!(!vk.data.is_empty(), "Verification key should not be empty");
        assert_eq!(vk.version, BlockProof::CURRENT_VERSION);
    }

    #[test]
    fn test_proof_generation() {
        let prover = BlockProver::new(5, 10).unwrap();
        let witness = create_test_witness(2);

        let proof = prover.prove(&witness);
        assert!(proof.is_ok(), "Proof generation should succeed: {:?}", proof.err());

        let proof = proof.unwrap();
        assert_eq!(proof.height, 1);
        assert_eq!(proof.tx_count, 2);
        assert!(!proof.proof.is_empty(), "Proof bytes should not be empty");
    }

    #[test]
    fn test_empty_block_proof() {
        let prover = BlockProver::new(5, 10).unwrap();
        let witness = create_test_witness(0);

        let proof = prover.prove(&witness);
        assert!(proof.is_ok(), "Empty block proof should succeed");

        let proof = proof.unwrap();
        assert_eq!(proof.tx_count, 0);
    }

    #[test]
    fn test_invalid_witness_rejected() {
        let prover = BlockProver::new(5, 10).unwrap();

        // Create witness with insufficient balance
        let transactions = vec![PaymentWitness {
            sender: [1u8; 32],
            recipient: [2u8; 32],
            amount: 1000, // Trying to send 1000
            signature: [0u8; 64],
            sender_balance_before: 100, // But only has 100
            sender_merkle_proof: MerkleProof::new(0, vec![[0u8; 32]; 10]),
            recipient_balance_before: 0,
            recipient_merkle_proof: MerkleProof::new(1, vec![[0u8; 32]; 10]),
        }];

        let witness = BlockWitness::new(
            1,
            StateSnapshot::new([1u8; 32], vec![]),
            transactions,
            StateSnapshot::new([2u8; 32], vec![]),
        );

        let result = prover.prove(&witness);
        assert!(result.is_err(), "Invalid witness should be rejected");
    }

    #[test]
    fn test_bytes_to_field() {
        let bytes = [1u8; 32];
        let field = bytes_to_field(&bytes);
        assert!(field.is_ok(), "Should convert bytes to field");

        // All zeros should work
        let zero_bytes = [0u8; 32];
        let zero_field = bytes_to_field(&zero_bytes);
        assert!(zero_field.is_ok(), "Should convert zero bytes");
    }

    // Tests for V2 (state transition) proving

    #[test]
    fn test_prover_with_state_transitions() {
        let prover = BlockProver::new_with_state_transitions(5, 10);
        assert!(prover.is_ok(), "Prover should be created");

        let prover = prover.unwrap();
        assert!(prover.uses_state_transitions());
    }

    #[test]
    fn test_prove_v2_empty_block() {
        let prover = BlockProver::new_with_state_transitions(5, 10).unwrap();
        let witness = BlockWitnessV2::empty(1, [42u8; 32], 10);

        let proof = prover.prove_v2(&witness);
        assert!(
            proof.is_ok(),
            "Empty block V2 proof should succeed: {:?}",
            proof.err()
        );

        let proof = proof.unwrap();
        assert_eq!(proof.tx_count, 0);
        assert_eq!(proof.prev_state_root, proof.new_state_root);
    }

    #[test]
    fn test_prove_v2_with_transactions() {
        let prover = BlockProver::new_with_state_transitions(5, 10).unwrap();
        let witness = create_test_witness_v2(2);

        let result = prover.prove_v2(&witness);

        // Note: This may not be satisfied due to placeholder intermediate roots
        // In production, we'd compute proper intermediate roots
        if let Ok(proof) = result {
            assert_eq!(proof.height, 1);
            assert_eq!(proof.tx_count, 2);
            assert!(!proof.proof.is_empty());
        }
    }

    #[test]
    fn test_prove_v2_invalid_witness() {
        let prover = BlockProver::new_with_state_transitions(5, 10).unwrap();

        // Create witness with insufficient balance
        let transitions = vec![PaymentTransitionWitness::new(
            50,  // Only 50
            500,
            100, // Trying to send 100
            0,
            MerkleProof::new(0, vec![[0u8; 32]; 10]),
            1,
            MerkleProof::new(1, vec![[0u8; 32]; 10]),
        )];

        let witness = BlockWitnessV2::new(1, [1u8; 32], [2u8; 32], transitions, 10);

        let result = prover.prove_v2(&witness);
        assert!(result.is_err(), "Invalid witness should be rejected");
    }

    #[test]
    fn test_prover_modes_different_ids() {
        let legacy_prover = BlockProver::new(5, 10).unwrap();
        let v2_prover = BlockProver::new_with_state_transitions(5, 10).unwrap();

        // They should have different prover IDs
        let legacy_vk = legacy_prover.verification_key();
        let v2_vk = v2_prover.verification_key();

        assert_ne!(
            legacy_vk.data[0..32],
            v2_vk.data[0..32],
            "Different modes should have different prover IDs"
        );
    }
}
