//! Core types for Ghost Pay ZK proofs

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

// =============================================================================
// Groth16 Proof Constants
// =============================================================================

/// Size of a Groth16 proof in bytes
/// - A point (G1): 48 bytes (compressed BLS12-381)
/// - B point (G2): 96 bytes (compressed BLS12-381)
/// - C point (G1): 48 bytes (compressed BLS12-381)
///
/// Total: 192 bytes
pub const GROTH16_PROOF_SIZE: usize = 192;

/// Size of a G1 point (compressed)
pub const G1_POINT_SIZE: usize = 48;

/// Size of a G2 point (compressed)
pub const G2_POINT_SIZE: usize = 96;

/// Minimum valid proof size (must have at least the header)
pub const MIN_PROOF_SIZE: usize = GROTH16_PROOF_SIZE;

/// Proof that a block's state transition is valid
///
/// This proof is generated by the block proposer and verified by validators.
/// Once verified and the block is finalized, the proof can be discarded.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BlockProof {
    /// Block height
    pub height: u64,
    /// Previous state root (public input)
    pub prev_state_root: [u8; 32],
    /// New state root (public input)
    pub new_state_root: [u8; 32],
    /// Number of transactions in the block
    pub tx_count: u32,
    /// The serialized proof bytes
    pub proof: Vec<u8>,
    /// Proof system version (for future upgrades)
    pub version: u8,
}

impl BlockProof {
    /// Current proof version
    pub const CURRENT_VERSION: u8 = 1;

    /// Get the public inputs for verification
    pub fn public_inputs(&self) -> Vec<[u8; 32]> {
        vec![self.prev_state_root, self.new_state_root]
    }

    /// Get proof size in bytes
    pub fn size(&self) -> usize {
        self.proof.len()
    }

    /// Create a new block proof
    pub fn new(
        height: u64,
        prev_state_root: [u8; 32],
        new_state_root: [u8; 32],
        tx_count: u32,
        proof: Vec<u8>,
    ) -> Self {
        Self {
            height,
            prev_state_root,
            new_state_root,
            tx_count,
            proof,
            version: Self::CURRENT_VERSION,
        }
    }
}

/// Witness data for proving a block (private inputs)
///
/// This contains all the data needed to generate a proof that
/// the state transition is valid.
#[derive(Debug, Clone)]
pub struct BlockWitness {
    /// Block height
    pub height: u64,
    /// State before applying transactions
    pub prev_state: StateSnapshot,
    /// Transactions to apply (with merkle proofs)
    pub transactions: Vec<PaymentWitness>,
    /// State after applying transactions
    pub new_state: StateSnapshot,
}

impl BlockWitness {
    /// Create a new block witness
    pub fn new(
        height: u64,
        prev_state: StateSnapshot,
        transactions: Vec<PaymentWitness>,
        new_state: StateSnapshot,
    ) -> Self {
        Self {
            height,
            prev_state,
            transactions,
            new_state,
        }
    }

    /// Number of transactions in the witness
    pub fn tx_count(&self) -> usize {
        self.transactions.len()
    }

    /// Validate witness consistency (balances add up, etc.)
    pub fn validate(&self) -> Result<(), WitnessValidationError> {
        // Check each payment has valid balance transition
        for (i, tx) in self.transactions.iter().enumerate() {
            if tx.sender_balance_before < tx.amount {
                return Err(WitnessValidationError::InsufficientBalance {
                    tx_index: i,
                    balance: tx.sender_balance_before,
                    amount: tx.amount,
                });
            }
        }

        Ok(())
    }
}

/// Witness validation error
#[derive(Debug, Clone)]
pub enum WitnessValidationError {
    /// Sender has insufficient balance
    InsufficientBalance {
        tx_index: usize,
        balance: u64,
        amount: u64,
    },
    /// Merkle proof is invalid
    InvalidMerkleProof { tx_index: usize },
    /// State roots don't match
    StateRootMismatch,
}

impl std::fmt::Display for WitnessValidationError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::InsufficientBalance {
                tx_index,
                balance,
                amount,
            } => {
                write!(
                    f,
                    "Transaction {} has insufficient balance: {} < {}",
                    tx_index, balance, amount
                )
            }
            Self::InvalidMerkleProof { tx_index } => {
                write!(f, "Transaction {} has invalid merkle proof", tx_index)
            }
            Self::StateRootMismatch => {
                write!(f, "State roots don't match after applying transactions")
            }
        }
    }
}

impl std::error::Error for WitnessValidationError {}

/// Witness for a single payment transaction
#[derive(Debug, Clone)]
pub struct PaymentWitness {
    /// Sender's Ghost ID (32 bytes)
    pub sender: [u8; 32],
    /// Recipient's Ghost ID (32 bytes)
    pub recipient: [u8; 32],
    /// Amount in satoshis
    pub amount: u64,
    /// Sender's Schnorr signature (64 bytes)
    pub signature: [u8; 64],
    /// Sender's balance before this payment
    pub sender_balance_before: u64,
    /// Merkle proof for sender's balance in previous state
    pub sender_merkle_proof: MerkleProof,
    /// Recipient's balance before this payment
    pub recipient_balance_before: u64,
    /// Merkle proof for recipient's balance in previous state
    pub recipient_merkle_proof: MerkleProof,
}

impl PaymentWitness {
    /// Sender's balance after this payment
    pub fn sender_balance_after(&self) -> u64 {
        self.sender_balance_before.saturating_sub(self.amount)
    }

    /// Recipient's balance after this payment
    pub fn recipient_balance_after(&self) -> u64 {
        self.recipient_balance_before.saturating_add(self.amount)
    }

    /// Create signing message for this payment
    pub fn signing_message(&self) -> [u8; 32] {
        use sha2::{Digest, Sha256};
        let mut hasher = Sha256::new();
        hasher.update(b"GhostPay/Payment/v1");
        hasher.update(self.sender);
        hasher.update(self.recipient);
        hasher.update(self.amount.to_le_bytes());
        hasher.finalize().into()
    }
}

/// Snapshot of state at a point in time
#[derive(Debug, Clone)]
pub struct StateSnapshot {
    /// Merkle root of the balance tree
    pub root: [u8; 32],
    /// Affected balances (only accounts touched by this block)
    /// Map from account ID to balance
    pub balances: Vec<([u8; 32], u64)>,
}

impl StateSnapshot {
    /// Create a new state snapshot
    pub fn new(root: [u8; 32], balances: Vec<([u8; 32], u64)>) -> Self {
        Self { root, balances }
    }

    /// Create empty state snapshot
    pub fn empty() -> Self {
        Self {
            root: [0u8; 32],
            balances: Vec::new(),
        }
    }

    /// Get balance for an account
    pub fn get_balance(&self, account: &[u8; 32]) -> Option<u64> {
        self.balances
            .iter()
            .find(|(id, _)| id == account)
            .map(|(_, balance)| *balance)
    }
}

/// Merkle inclusion proof for a leaf in the balance tree
#[derive(Debug, Clone)]
pub struct MerkleProof {
    /// Index of the leaf in the tree
    pub leaf_index: u64,
    /// Sibling hashes from leaf to root
    pub siblings: Vec<[u8; 32]>,
}

impl MerkleProof {
    /// Create a new merkle proof
    pub fn new(leaf_index: u64, siblings: Vec<[u8; 32]>) -> Self {
        Self {
            leaf_index,
            siblings,
        }
    }

    /// Depth of the merkle tree (number of siblings)
    pub fn depth(&self) -> usize {
        self.siblings.len()
    }

    /// Verify this proof against a root
    pub fn verify(&self, leaf_hash: [u8; 32], root: [u8; 32]) -> bool {
        let computed_root = self.compute_root(leaf_hash);
        computed_root == root
    }

    /// Compute the root from a leaf hash
    pub fn compute_root(&self, leaf_hash: [u8; 32]) -> [u8; 32] {
        use sha2::{Digest, Sha256};

        let mut current = leaf_hash;
        let mut index = self.leaf_index;

        for sibling in &self.siblings {
            let mut hasher = Sha256::new();

            if index.is_multiple_of(2) {
                // Current is left child
                hasher.update(current);
                hasher.update(sibling);
            } else {
                // Current is right child
                hasher.update(sibling);
                hasher.update(current);
            }

            current = hasher.finalize().into();
            index /= 2;
        }

        current
    }
}

/// Verification key for block proofs
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VerificationKey {
    /// Serialized verification key bytes
    pub data: Vec<u8>,
    /// Version of the verification key
    pub version: u8,
}

impl VerificationKey {
    /// Create a new verification key
    pub fn new(data: Vec<u8>) -> Self {
        Self {
            data,
            version: BlockProof::CURRENT_VERSION,
        }
    }
}

/// Proving parameters for block proofs
#[derive(Debug, Clone)]
pub struct ProvingParams {
    /// Serialized proving parameters
    pub data: Vec<u8>,
    /// Maximum transactions per block this params supports
    pub max_txs: usize,
    /// Merkle tree depth this params supports
    pub tree_depth: usize,
    /// Version
    pub version: u8,
}

impl ProvingParams {
    /// Create new proving params
    pub fn new(data: Vec<u8>, max_txs: usize, tree_depth: usize) -> Self {
        Self {
            data,
            max_txs,
            tree_depth,
            version: BlockProof::CURRENT_VERSION,
        }
    }
}

// ============================================================================
// Enhanced witness types for full ZK state transitions
// ============================================================================

/// Witness for a single payment's state transition
///
/// Contains all data needed to prove that a payment correctly
/// transitions state from one merkle root to another.
#[derive(Debug, Clone)]
pub struct PaymentTransitionWitness {
    /// Sender's balance before this payment
    pub sender_balance_before: u64,
    /// Recipient's balance before this payment
    pub recipient_balance_before: u64,
    /// Payment amount
    pub amount: u64,

    /// Sender's leaf index in the tree
    pub sender_index: u64,
    /// Merkle proof for sender's balance
    pub sender_merkle_proof: MerkleProof,

    /// Recipient's leaf index in the tree
    pub recipient_index: u64,
    /// Merkle proof for recipient's balance (against intermediate root)
    pub recipient_merkle_proof: MerkleProof,
}

impl PaymentTransitionWitness {
    /// Create a new payment transition witness
    pub fn new(
        sender_balance_before: u64,
        recipient_balance_before: u64,
        amount: u64,
        sender_index: u64,
        sender_merkle_proof: MerkleProof,
        recipient_index: u64,
        recipient_merkle_proof: MerkleProof,
    ) -> Self {
        Self {
            sender_balance_before,
            recipient_balance_before,
            amount,
            sender_index,
            sender_merkle_proof,
            recipient_index,
            recipient_merkle_proof,
        }
    }

    /// Sender's balance after this payment
    pub fn sender_balance_after(&self) -> u64 {
        self.sender_balance_before.saturating_sub(self.amount)
    }

    /// Recipient's balance after this payment
    pub fn recipient_balance_after(&self) -> u64 {
        self.recipient_balance_before.saturating_add(self.amount)
    }

    /// Validate that the witness is internally consistent
    pub fn validate(&self) -> Result<(), WitnessValidationError> {
        if self.sender_balance_before < self.amount {
            return Err(WitnessValidationError::InsufficientBalance {
                tx_index: 0,
                balance: self.sender_balance_before,
                amount: self.amount,
            });
        }
        Ok(())
    }
}

/// Enhanced block witness with full merkle proof data for ZK state transitions
///
/// This witness type enables fully trustless verification where
/// the state root transition is proven cryptographically.
#[derive(Debug, Clone)]
pub struct BlockWitnessV2 {
    /// Block height
    pub height: u64,
    /// Previous state root
    pub prev_state_root: [u8; 32],
    /// New state root (after all payments)
    pub new_state_root: [u8; 32],
    /// Payment transitions with merkle proofs
    pub transitions: Vec<PaymentTransitionWitness>,
    /// Merkle tree depth
    pub tree_depth: usize,
}

impl BlockWitnessV2 {
    /// Create a new block witness
    pub fn new(
        height: u64,
        prev_state_root: [u8; 32],
        new_state_root: [u8; 32],
        transitions: Vec<PaymentTransitionWitness>,
        tree_depth: usize,
    ) -> Self {
        Self {
            height,
            prev_state_root,
            new_state_root,
            transitions,
            tree_depth,
        }
    }

    /// Create an empty block witness (no transactions)
    pub fn empty(height: u64, state_root: [u8; 32], tree_depth: usize) -> Self {
        Self {
            height,
            prev_state_root: state_root,
            new_state_root: state_root,
            transitions: Vec::new(),
            tree_depth,
        }
    }

    /// Number of transactions in the witness
    pub fn tx_count(&self) -> usize {
        self.transitions.len()
    }

    /// Validate witness consistency
    pub fn validate(&self) -> Result<(), WitnessValidationError> {
        for (i, tx) in self.transitions.iter().enumerate() {
            if tx.sender_balance_before < tx.amount {
                return Err(WitnessValidationError::InsufficientBalance {
                    tx_index: i,
                    balance: tx.sender_balance_before,
                    amount: tx.amount,
                });
            }
        }
        Ok(())
    }

    /// Convert to legacy BlockWitness format (for backwards compatibility)
    pub fn to_legacy(&self) -> BlockWitness {
        let transactions = self
            .transitions
            .iter()
            .map(|t| PaymentWitness {
                sender: [0u8; 32], // Not used in legacy format
                recipient: [0u8; 32],
                amount: t.amount,
                signature: [0u8; 64],
                sender_balance_before: t.sender_balance_before,
                sender_merkle_proof: t.sender_merkle_proof.clone(),
                recipient_balance_before: t.recipient_balance_before,
                recipient_merkle_proof: t.recipient_merkle_proof.clone(),
            })
            .collect();

        BlockWitness {
            height: self.height,
            prev_state: StateSnapshot::new(self.prev_state_root, vec![]),
            transactions,
            new_state: StateSnapshot::new(self.new_state_root, vec![]),
        }
    }
}

/// Intermediate root computed during state transitions
///
/// Tracks the state root after each payment in a block.
#[derive(Debug, Clone)]
pub struct IntermediateRoot {
    /// The root value
    pub root: [u8; 32],
    /// Index of the payment that produced this root (0 = after first payment)
    pub after_payment_index: usize,
}

/// Account state for building merkle trees
#[derive(Debug, Clone, Default)]
pub struct AccountState {
    /// Account index in the tree
    pub index: u64,
    /// Current balance
    pub balance: u64,
}

/// Sparse representation of account balances
pub type AccountBalances = HashMap<u64, u64>;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_merkle_proof_basic() {
        // Simple 2-level tree
        let leaf = [1u8; 32];
        let sibling = [2u8; 32];

        let proof = MerkleProof::new(0, vec![sibling]);

        let root = proof.compute_root(leaf);
        assert!(proof.verify(leaf, root));

        // Wrong root should fail
        let wrong_root = [0u8; 32];
        assert!(!proof.verify(leaf, wrong_root));
    }

    #[test]
    fn test_payment_witness_balance_after() {
        let witness = PaymentWitness {
            sender: [1u8; 32],
            recipient: [2u8; 32],
            amount: 100,
            signature: [0u8; 64],
            sender_balance_before: 500,
            sender_merkle_proof: MerkleProof::new(0, vec![]),
            recipient_balance_before: 200,
            recipient_merkle_proof: MerkleProof::new(1, vec![]),
        };

        assert_eq!(witness.sender_balance_after(), 400);
        assert_eq!(witness.recipient_balance_after(), 300);
    }

    #[test]
    fn test_witness_validation() {
        let witness = BlockWitness {
            height: 1,
            prev_state: StateSnapshot::empty(),
            transactions: vec![PaymentWitness {
                sender: [1u8; 32],
                recipient: [2u8; 32],
                amount: 100,
                signature: [0u8; 64],
                sender_balance_before: 50, // Less than amount!
                sender_merkle_proof: MerkleProof::new(0, vec![]),
                recipient_balance_before: 0,
                recipient_merkle_proof: MerkleProof::new(1, vec![]),
            }],
            new_state: StateSnapshot::empty(),
        };

        let result = witness.validate();
        assert!(matches!(
            result,
            Err(WitnessValidationError::InsufficientBalance { .. })
        ));
    }

    #[test]
    fn test_block_proof_creation() {
        let proof = BlockProof::new(100, [1u8; 32], [2u8; 32], 5, vec![0u8; 128]);

        assert_eq!(proof.height, 100);
        assert_eq!(proof.tx_count, 5);
        assert_eq!(proof.size(), 128);
        assert_eq!(proof.version, BlockProof::CURRENT_VERSION);
    }

    // Tests for enhanced witness types

    #[test]
    fn test_payment_transition_witness() {
        let witness = PaymentTransitionWitness::new(
            1000, // sender balance
            500,  // recipient balance
            100,  // amount
            0,    // sender index
            MerkleProof::new(0, vec![[0u8; 32]; 10]),
            1, // recipient index
            MerkleProof::new(1, vec![[0u8; 32]; 10]),
        );

        assert_eq!(witness.sender_balance_after(), 900);
        assert_eq!(witness.recipient_balance_after(), 600);
        assert!(witness.validate().is_ok());
    }

    #[test]
    fn test_payment_transition_insufficient_balance() {
        let witness = PaymentTransitionWitness::new(
            50,  // sender only has 50
            500, // recipient balance
            100, // trying to send 100
            0,
            MerkleProof::new(0, vec![]),
            1,
            MerkleProof::new(1, vec![]),
        );

        assert!(witness.validate().is_err());
    }

    #[test]
    fn test_block_witness_v2() {
        let transitions = vec![
            PaymentTransitionWitness::new(
                1000,
                500,
                100,
                0,
                MerkleProof::new(0, vec![[0u8; 32]; 10]),
                1,
                MerkleProof::new(1, vec![[0u8; 32]; 10]),
            ),
            PaymentTransitionWitness::new(
                2000,
                300,
                50,
                2,
                MerkleProof::new(2, vec![[0u8; 32]; 10]),
                3,
                MerkleProof::new(3, vec![[0u8; 32]; 10]),
            ),
        ];

        let witness = BlockWitnessV2::new(1, [1u8; 32], [2u8; 32], transitions, 10);

        assert_eq!(witness.height, 1);
        assert_eq!(witness.tx_count(), 2);
        assert_eq!(witness.tree_depth, 10);
        assert!(witness.validate().is_ok());
    }

    #[test]
    fn test_block_witness_v2_empty() {
        let witness = BlockWitnessV2::empty(1, [42u8; 32], 20);

        assert_eq!(witness.tx_count(), 0);
        assert_eq!(witness.prev_state_root, witness.new_state_root);
        assert!(witness.validate().is_ok());
    }

    #[test]
    fn test_block_witness_v2_to_legacy() {
        let transitions = vec![PaymentTransitionWitness::new(
            1000,
            500,
            100,
            0,
            MerkleProof::new(0, vec![[0u8; 32]; 5]),
            1,
            MerkleProof::new(1, vec![[0u8; 32]; 5]),
        )];

        let witness_v2 = BlockWitnessV2::new(1, [1u8; 32], [2u8; 32], transitions, 5);

        let legacy = witness_v2.to_legacy();

        assert_eq!(legacy.height, 1);
        assert_eq!(legacy.tx_count(), 1);
        assert_eq!(legacy.transactions[0].amount, 100);
        assert_eq!(legacy.transactions[0].sender_balance_before, 1000);
    }
}
